<?php if($block->getData('golliusername')): ?>
    <iframe src="https://gol.li/<?php echo $block->getData('golliusername'); ?>/share?<?php if($block->getData('golliwidgetbg')): ?>bg=<?php echo substr($block->getData('golliwidgetbg'), 1); ?>&<?php endif; ?><?php if($block->getData('golliwidgetborder')): ?>b=<?php echo substr($block->getData('golliwidgetborder'), 1); ?><?php endif; ?>"
            style="width: 100%;
                   max-width: <?php echo $block->getData('golliwidgetwidth'); ?>px;
                   height: <?php echo $block->getData('golliwidgetheight'); ?>px;
                   border: 1px solid <?php if($block->getData('golliwidgetborder')): ?><?php echo $block->getData('golliwidgetborder'); ?><?php else: ?>#ccc<?php endif; ?>;"></iframe>
<?php endif; ?>